[project]
name = 'QVFHN'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.quantum-detector-management]
path = 'contracts/quantum-detector-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.quantum-energy-marketplace]
path = 'contracts/quantum-energy-marketplace.clar'
clarity_version = 2
epoch = 2.5

[contracts.vacuum-energy-nft]
path = 'contracts/vacuum-energy-nft.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
